version: '2'
services:
  transformimgs:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/go/src/github.com/Pixboost/transformimgs
    environment:
      MAGICK_TIME_LIMIT: "90"
    ports:
      - "7706:8080"