version: '2'
services:
  transformimgs:
    build:
      context: ../
      dockerfile: Dockerfile
    # volumes:
      # - ../:/go/src/github.com/Pixboost/transformimgs
    environment:
      MAGICK_TIME_LIMIT: "90"
  imgserver:
    image: caddy:2.4.6
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/site
      - /Users/stevekim/Development/CMES/on-site-api/images:/site/img
    ports:
      - "7706:80"
      # - "443:443"